default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: [ "payment_gateway", "payments" ]
      threads: 4
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: [ "whatsapp_meta", "whatsapp" ]
      threads: 4
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: [ "geo_broadcast", "broadcast", "cleanup" ]
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: [ "notifications_mail", "mailers", "notifications", "default" ]
      threads: 4
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.2
    - queues: [ "pdf_reports", "reports" ]
      threads: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.5
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 0.5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
