default: &default
  dispatchers: []
  workers:
    - queues: [ "pdf_reports", "reports" ]
      threads: <%= ENV.fetch("REPORTS_WORKER_THREADS", 3) %>
      processes: <%= ENV.fetch("REPORTS_WORKER_PROCESSES", 1) %>
      polling_interval: 0.5

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
